# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
